name: Trigger auto deployment for acaport02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/acaport02-AutoDeployTrigger-a298c37e-f225-4ece-94ce-74a077c57319.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACAPORT02_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAPORT02_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAPORT02_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ACAPORT02_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAPORT02_REGISTRY_PASSWORD }}
          containerAppName: acaport02
          resourceGroup: expresssampledeletea409
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


